;;
;;  cffi-id3tag  -  Common Lisp wrapper for libid3tag
;;
;;  Copyright 2018 Thomas de Grivel <thoxdg@gmail.com>
;;
;;  Permission to use, copy, modify, and distribute this software for any
;;  purpose with or without fee is hereby granted, provided that the above
;;  copyright notice and this permission notice appear in all copies.
;;
;;  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
;;  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
;;  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
;;  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
;;  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
;;  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
;;  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
;;

(in-package :common-lisp)

(defpackage :cffi-id3tag
  (:nicknames :id3tag)
  (:use
   :cffi
   :common-lisp)
  (:export
   #:+id3-author+
   #:+id3-email+
   #:+id3-field-textencoding-iso-8859-1+
   #:+id3-field-textencoding-utf-16+
   #:+id3-field-textencoding-utf-16be+
   #:+id3-field-textencoding-utf-8+
   #:+id3-field-type-binarydata+
   #:+id3-field-type-date+
   #:+id3-field-type-frameid+
   #:+id3-field-type-int16+
   #:+id3-field-type-int24+
   #:+id3-field-type-int32+
   #:+id3-field-type-int32plus+
   #:+id3-field-type-int8+
   #:+id3-field-type-language+
   #:+id3-field-type-latin1+
   #:+id3-field-type-latin1full+
   #:+id3-field-type-latin1list+
   #:+id3-field-type-string+
   #:+id3-field-type-stringfull+
   #:+id3-field-type-stringlist+
   #:+id3-field-type-textencoding+
   #:+id3-file-mode-readonly+
   #:+id3-file-mode-readwrite+
   #:+id3-frame-album+
   #:+id3-frame-artist+
   #:+id3-frame-comment+
   #:+id3-frame-flag-compression+
   #:+id3-frame-flag-datalengthindicator+
   #:+id3-frame-flag-encryption+
   #:+id3-frame-flag-filealterpreservation+
   #:+id3-frame-flag-formatflags+
   #:+id3-frame-flag-groupingidentity+
   #:+id3-frame-flag-knownflags+
   #:+id3-frame-flag-readonly+
   #:+id3-frame-flag-statusflags+
   #:+id3-frame-flag-tagalterpreservation+
   #:+id3-frame-flag-unsynchronisation+
   #:+id3-frame-genre+
   #:+id3-frame-obsolete+
   #:+id3-frame-title+
   #:+id3-frame-track+
   #:+id3-frame-year+
   #:+id3-publishyear+
   #:+id3-tag-extendedflag-crcdatapresent+
   #:+id3-tag-extendedflag-knownflags+
   #:+id3-tag-extendedflag-tagisanupdate+
   #:+id3-tag-extendedflag-tagrestrictions+
   #:+id3-tag-flag-experimentalindicator+
   #:+id3-tag-flag-extendedheader+
   #:+id3-tag-flag-footerpresent+
   #:+id3-tag-flag-knownflags+
   #:+id3-tag-flag-unsynchronisation+
   #:+id3-tag-option-appendedtag+
   #:+id3-tag-option-compression+
   #:+id3-tag-option-crc+
   #:+id3-tag-option-filealtered+
   #:+id3-tag-option-id3v1+
   #:+id3-tag-option-unsynchronisation+
   #:+id3-tag-querysize+
   #:+id3-tag-restriction-imageencoding-mask+
   #:+id3-tag-restriction-imageencoding-none+
   #:+id3-tag-restriction-imageencoding-png-jpeg+
   #:+id3-tag-restriction-imagesize-256-256+
   #:+id3-tag-restriction-imagesize-64-64+
   #:+id3-tag-restriction-imagesize-64-64-exact+
   #:+id3-tag-restriction-imagesize-mask+
   #:+id3-tag-restriction-imagesize-none+
   #:+id3-tag-restriction-tagsize-128-frames-1-mb+
   #:+id3-tag-restriction-tagsize-32-frames-4-kb+
   #:+id3-tag-restriction-tagsize-32-frames-40-kb+
   #:+id3-tag-restriction-tagsize-64-frames-128-kb+
   #:+id3-tag-restriction-tagsize-mask+
   #:+id3-tag-restriction-textencoding-latin1-utf8+
   #:+id3-tag-restriction-textencoding-mask+
   #:+id3-tag-restriction-textencoding-none+
   #:+id3-tag-restriction-textsize-1024-chars+
   #:+id3-tag-restriction-textsize-128-chars+
   #:+id3-tag-restriction-textsize-30-chars+
   #:+id3-tag-restriction-textsize-mask+
   #:+id3-tag-restriction-textsize-none+
   #:+id3-tag-version+
   #:+id3-version+
   #:+id3-version-extra+
   #:+id3-version-major+
   #:+id3-version-minor+
   #:+id3-version-patch+
   #:c-id3-field-addstring
   #:c-id3-field-getbinarydata
   #:c-id3-field-getframeid
   #:c-id3-field-getfulllatin1
   #:c-id3-field-getfullstring
   #:c-id3-field-getint
   #:c-id3-field-getlatin1
   #:c-id3-field-getnstrings
   #:c-id3-field-getstring
   #:c-id3-field-getstrings
   #:c-id3-field-gettextencoding
   #:c-id3-field-setbinarydata
   #:c-id3-field-setframeid
   #:c-id3-field-setfulllatin1
   #:c-id3-field-setfullstring
   #:c-id3-field-setint
   #:c-id3-field-setlanguage
   #:c-id3-field-setlatin1
   #:c-id3-field-setstring
   #:c-id3-field-setstrings
   #:c-id3-field-settextencoding
   #:c-id3-field-type
   #:c-id3-file-close
   #:c-id3-file-fdopen
   #:c-id3-file-open
   #:c-id3-file-tag
   #:c-id3-frame-delete
   #:c-id3-frame-field
   #:c-id3-frame-new
   #:c-id3-genre-index
   #:c-id3-genre-name
   #:c-id3-genre-number
   #:c-id3-latin1-ucs4duplicate
   #:c-id3-tag-attachframe
   #:c-id3-tag-clearframes
   #:c-id3-tag-delete
   #:c-id3-tag-detachframe
   #:c-id3-tag-findframe
   #:c-id3-tag-new
   #:c-id3-tag-options
   #:c-id3-tag-parse
   #:c-id3-tag-query
   #:c-id3-tag-render
   #:c-id3-tag-setlength
   #:c-id3-tag-version
   #:c-id3-ucs4-getnumber
   #:c-id3-ucs4-latin1duplicate
   #:c-id3-ucs4-putnumber
   #:c-id3-ucs4-utf16duplicate
   #:c-id3-ucs4-utf8duplicate
   #:c-id3-utf16-ucs4duplicate
   #:c-id3-utf8-ucs4duplicate
   #:id3-author
   #:id3-build
   #:id3-byte-t
   #:id3-copyright
   #:id3-field
   #:id3-field-addstring
   #:id3-field-binary
   #:id3-field-binary-tclass
   #:id3-field-getbinarydata
   #:id3-field-getframeid
   #:id3-field-getfullstring
   #:id3-field-getint
   #:id3-field-getnstrings
   #:id3-field-getstrings
   #:id3-field-gettextencoding
   #:id3-field-immediate
   #:id3-field-immediate-tclass
   #:id3-field-latin1
   #:id3-field-latin1-tclass
   #:id3-field-latin1list
   #:id3-field-latin1list-tclass
   #:id3-field-number
   #:id3-field-number-tclass
   #:id3-field-setbinarydata
   #:id3-field-setframeid
   #:id3-field-setfulllatin1
   #:id3-field-setfullstring
   #:id3-field-setint
   #:id3-field-setlanguage
   #:id3-field-setlatin1
   #:id3-field-setstring
   #:id3-field-setstrings
   #:id3-field-settextencoding
   #:id3-field-string
   #:id3-field-string-tclass
   #:id3-field-stringlist
   #:id3-field-stringlist-tclass
   #:id3-field-textencoding
   #:id3-field-type
   #:id3-file
   #:id3-file-mode
   #:id3-file-open
   #:id3-file-close
   #:id3-frame
   #:id3-frame-delete
   #:id3-frame-field
   #:id3-frame-tclass
   #:id3-genre-index
   #:id3-genre-name
   #:id3-genre-number
   #:id3-latin1
   #:id3-latin1-t
   #:id3-latin1-ucs4duplicate
   #:id3-length-t
   #:id3-tag
   #:id3-tag-clearframes
   #:id3-tag-detachframe
   #:id3-tag-findframe
   #:id3-tag-options
   #:id3-tag-query
   #:id3-tag-render
   #:id3-tag-setlength
   #:id3-tag-tclass
   #:id3-tag-version
   #:id3-ucs4-getnumber
   #:id3-ucs4-putnumber
   #:id3-ucs4-t
   #:id3-ucs4-utf16duplicate
   #:id3-ucs4-utf8duplicate
   #:id3-utf16-t
   #:id3-utf8-t
   #:id3-utf8-ucs4duplicate
   #:id3-version))
